# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: # Hace referencia al disparador
- master # En este caso cuando se haga una acción sobre la rama master.

pool: # El pool de forma global quiere decir que usaremos esta config para todos los jobs
  vmImage: ubuntu-latest # En este caso estoy usando la imagen de ubuntu-latest

steps: # Esto son los pasos a seguir para el despliegue
- script: | # Este es un script multilínea, el | representa esta opci'on de multi linea
    echo "TEST ME"
  displayName: 'npm install and build' # Nombre a mostrar en pantalla
