name: 'Test-workflow'

on: 
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
        test: ['Test it']
    steps:
      - name: 'Run echo'
        run: echo 'Test me ok' && echo 'Node version ${{matrix.node-version}}' && echo ' test ${{matrix.test}}'

      
